In [1]:
import pandas as pd
import numpy as np

# Load resources

In [21]:
def load_pathway(fpath):
    result = []
    with open(fpath) as f:
        for line in f:
            split_line = [x for x in line.strip().split('\t') if x]  # Remove empty strings directly

            row = {'label': split_line[0]}
            for gene in split_line[1:]:
                row[gene] = 1

            result.append(row)

    df = pd.DataFrame(result)
    df = df.fillna(0.0).set_index('label').astype(bool).T  # Chained operations for clarity

    return df

mpath = "PanglaoDB_Augmented_2021.txt"
pang = load_pathway(mpath)

cell_types = [
    'Fibroblasts',
    'Myocytes',
    'Myoblasts',
    'Myofibroblasts',
]

subset = pang[cell_types]
panglao_markers = subset[subset.any(axis=1)]

panglao_markers = panglao_markers.reset_index(names='gene')

print(panglao_markers.shape)
panglao_markers.head()

# fib_genes = panglao_markers['Fibroblasts'] == True
# fib_genes =  panglao_markers[fib_genes].index
# print(f"N fib genes: {len(fib_genes)}")

# myo_genes_panglao = (panglao_markers['Myocytes'] == True) | (panglao_markers['Myoblasts'] == True)
# myo_genes_panglao =  panglao_markers[myo_genes_panglao].index
# print(f"N myocyte/myoblast genes: {len(myo_genes_panglao)}")

(451, 5)

label     gene  Fibroblasts  Myocytes  Myoblasts  Myofibroblasts
0      RARRES2         True     False      False           False
1        CELA1         True     False      False           False
2          LUM         True     False       True            True
3        PRRX1         True      True       True            True
4       SCARA5         True     False      False           False

In [5]:
# fpath = "Tabula_Sapiens.txt"

# tabula = load_pathway(fpath)
# tabula.head()


# cell_types = [
#     'Muscle-fast Muscle Cell',
#     'Muscle-slow Muscle Cell',

label,Bladder-bladder Urothelial Cell,Bladder-capillary Endothelial Cell,Bladder-endothelial Cell Of Lymphatic Vessel,Bladder-fibroblast,Bladder-macrophage,Bladder-mast Cell,Bladder-myofibroblast Cell,Bladder-nk Cell,Bladder-pericyte Cell,Bladder-plasma Cell,...,Thymus-dn4 Thymocyte,Thymus-innate Lymphoid Cell,Thymus-myeloid Dendritic Cell,Thymus-naive Regulatory T Cell,Thymus-t Follicular Helper Cell,Tongue-schwann Cell,Vasculature-artery Endothelial Cell,Vasculature-lymphatic Endothelial Cell,Eye-adipocyte,Eye-retinal Ganglion Cell
GDF15,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
RPS8,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
RPL21,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
RPS9,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,False
RPS6,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [8]:
# [col for col in tabula.columns if 'skeletal' in col.lower()]

['Muscle-skeletal Muscle Satellite Stem Cell', 'Skin-cell Of Skeletal Muscle']

In [9]:
fpath = "CellMarker_2024.txt"

cellmarker = load_pathway(fpath)
cellmarker.head()

label,1-Cell Stage Cell (Blastomere) Embryo Human,1-Cell Stage Cell (Blastomere) Embryo Mouse,4-Cell Stage Cell (Blastomere) Embryo Human,4-Cell Stage Cell (Blastomere) Embryo Mouse,8-Cell Stage Cell (Blastomere) Embryo Human,8-Cell Stage Cell (Blastomere) Embryo Mouse,AXL+ SIGLEC6+ Dendritic Cell Undefined Human,AXL+SIGLEC6+ Dendritic Cell Blood Human,Acinar Cell Pancreas Human,Acinar Cell Pancreatic Islet Human,...,Vascular Endothelial Cell Eye Human,Vascular Endothelial Cell Kidney Mouse,Vascular Smooth Muscle cell(VSMC) Bone Mouse,Ventral Otocyst Brain Mouse,Well-established Epicardial Progenitor Cell Heart Mouse,Wnt2+ Cell Lung Mouse,hMSC-treated B Cell Bone Marrow Human,lmmLeydig Cell Testis Human,Proliferative Mesenchymal Progenitor Cell Lung Mouse,Beta-2M - SPalpha-6 + THY1 + Spermatogonial Stem Cell Testis Mouse
KLF11,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
KLHDC3,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
BLCAP,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
PPIL2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ARHGEF16,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [15]:
[col for col in cellmarker.columns if 'myoblast' in col.lower()]

['Myoblast Muscle Human',
 'Myoblast Skeletal Muscle Human',
 'Myoblast Undefined Human']

In [11]:
[col for col in cellmarker.columns if 'fibroblast' in col.lower()]

['Cancer-associated Fibroblast Breast Human',
 'Cancer-associated Fibroblast Colorectum Human',
 'Cancer-associated Fibroblast Liver Human',
 'Cancer-associated Fibroblast Skin Human',
 'Fibroblast Aorta Mouse',
 'Fibroblast Artery Mouse',
 'Fibroblast Bile Duct Human',
 'Fibroblast Bladder Human',
 'Fibroblast Blood Vessel Mouse',
 'Fibroblast Blood Human',
 'Fibroblast Brain Human',
 'Fibroblast Breast Human',
 'Fibroblast Breast Mouse',
 'Fibroblast Colon Human',
 'Fibroblast Epithelium Human',
 'Fibroblast Esophagus Human',
 'Fibroblast Heart Muscle Mouse',
 'Fibroblast Heart Human',
 'Fibroblast Heart Mouse',
 'Fibroblast Intestine Mouse',
 'Fibroblast Kidney Human',
 'Fibroblast Kidney Mouse',
 'Fibroblast Liver Mouse',
 'Fibroblast Lung Human',
 'Fibroblast Lung Mouse',
 'Fibroblast Muscle Human',
 'Fibroblast Muscle Mouse',
 'Fibroblast Ovarian Cortex Human',
 'Fibroblast Ovary Human',
 'Fibroblast Pancreas Human',
 'Fibroblast Prostate Human',
 'Fibroblast Skin Human',
 'Fibroblast Skin Mouse',
 'Fibroblast Spleen Human',
 'Fibroblast Stomach Human',
 'Fibroblast Synovium Human',
 'Fibroblast Thymus Human',
 'Fibroblast Undefined Human',
 'Fibroblast Undefined Mouse',
 'Fibroblast Vocal Fold Human',
 'Idiopathic Pulmonary Fibrosis Myofibroblast Undefined Human',
 'Lipofibroblast Lung Mouse',
 'Matrix Fibroblast Lung Mouse',
 'Myofibroblast Bone Mouse',
 'Myofibroblast Breast Human',
 'Myofibroblast Dermis Human',
 'Myofibroblast Epithelium Human',
 'Myofibroblast Esophagus Human',
 'Myofibroblast Heart Mouse',
 'Myofibroblast Lung Human',
 'Myofibroblast Lung Mouse',
 'Myofibroblast Skin Human',
 'Myofibroblast Stomach Human',
 'Myofibroblast Tendon Mouse',
 'Myofibroblast Undefined Human',
 'Myofibroblastic Cancer Associated Fibroblast (myCAF) Pancreas Human',
 'Papillary Fibroblast Skin Human',
 'Reticular Fibroblast Skin Human']

In [20]:
cell_types = [
    'Myoblast Skeletal Muscle Human',
    'Myoblast Muscle Human',
    
    'Fibroblast Skin Human',
    
    'Myofibroblast Skin Human',
]

cdf = cellmarker[cell_types].copy()
subset = cdf[cell_types]

cellmarker_markers = subset[subset.any(axis=1)]

cellmarker_markers = cellmarker_markers.reset_index(names='gene')

cellmarker_markers.head()

label,gene,Myoblast Skeletal Muscle Human,Myoblast Muscle Human,Fibroblast Skin Human,Myofibroblast Skin Human
0,CEL,False,False,True,False
1,ID3,False,True,False,False
2,COL1A2,False,False,True,False
3,CFD,False,False,True,False
4,LUM,False,False,True,False

# Combine

In [31]:
def markers_wide_to_long(df, gene_col="gene"):
    cell_cols = df.columns.drop(gene_col)
    long = (df
            .melt(id_vars=gene_col, value_vars=cell_cols,
                  var_name="cell_type", value_name="is_marker"))
    return long[long["is_marker"]].drop(columns="is_marker").reset_index(drop=True)


long1 = markers_wide_to_long(panglao_markers).assign(source='Panglao')
long2 = markers_wide_to_long(cellmarker_markers).assign(source='CellMarker')

mdf = (pd.concat([long1, long2], ignore_index=True)
       .drop_duplicates()
       .sort_values(['cell_type', 'gene'])
       .reset_index(drop=True))

print(mdf.shape)
mdf.head()

(699, 3)

    gene              cell_type      source
0   APOD  Fibroblast Skin Human  CellMarker
1   APOE  Fibroblast Skin Human  CellMarker
2  CCL19  Fibroblast Skin Human  CellMarker
3   CCL2  Fibroblast Skin Human  CellMarker
4   CD36  Fibroblast Skin Human  CellMarker

In [32]:
# add categories
ct = (mdf["cell_type"]
      .astype("string")
      .str.normalize("NFKC")
      .str.strip()
      .str.replace(r"\s+", " ", regex=True)
      .str.lower()
)

mdf["category"] = np.select(
    [
        ct.str.contains(r"\bmyofibroblasts?\b", regex=True, na=False),
        ct.str.contains(r"\bfibroblasts?\b", regex=True, na=False),
        ct.str.contains(r"\b(myocytes?|muscles?|myoblasts?)\b", regex=True, na=False),
    ],
    ["myofibroblast", "fibroblast", "muscle"],
    default=pd.NA
)

mdf.head()

/tmp/ipykernel_3107890/1260700923.py:17: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ct.str.contains(r"\b(myocytes?|muscles?|myoblasts?)\b", regex=True, na=False),

    gene              cell_type      source    category
0   APOD  Fibroblast Skin Human  CellMarker  fibroblast
1   APOE  Fibroblast Skin Human  CellMarker  fibroblast
2  CCL19  Fibroblast Skin Human  CellMarker  fibroblast
3   CCL2  Fibroblast Skin Human  CellMarker  fibroblast
4   CD36  Fibroblast Skin Human  CellMarker  fibroblast

In [37]:
gene_cats = (mdf.dropna(subset=["category"])
             .groupby("gene")["category"]
             .agg(lambda s: sorted(set(s))))

# 2) attach and compute "other_categories?"
tmp = mdf.join(gene_cats.rename("all_categories"), on="gene")

def other_cats(row):
    cats = row["all_categories"]
    cat = row["category"]
    if not isinstance(cats, list) or pd.isna(cat):
        return pd.NA
    if len(cats) == 1:
        return "unique"
    others = [c for c in cats if c != cat]
    return ", ".join(others) if others else "unique"

mdf["other_categories?"] = tmp.apply(other_cats, axis=1)
mdf.head()

    gene              cell_type      source    category other_categories?
0   APOD  Fibroblast Skin Human  CellMarker  fibroblast            unique
1   APOE  Fibroblast Skin Human  CellMarker  fibroblast            unique
2  CCL19  Fibroblast Skin Human  CellMarker  fibroblast            unique
3   CCL2  Fibroblast Skin Human  CellMarker  fibroblast            muscle
4   CD36  Fibroblast Skin Human  CellMarker  fibroblast            unique

In [38]:
# mdf.to_csv("clean_marker_genes.csv", index=False)

In [44]:
print(f"Total muscle markers: {mdf[mdf['category'] == 'muscle']['gene'].nunique()}")
print(f"Unique muscle markers: {mdf[(mdf['category'] == 'muscle') & (mdf['other_categories?'] == 'unique')]['gene'].nunique()}")

print(f"\nTotal fibroblast markers: {mdf[mdf['category'] == 'fibroblast']['gene'].nunique()}")
print(f"Unique fibroblast markers: {mdf[(mdf['category'] == 'fibroblast') & (mdf['other_categories?'] == 'unique')]['gene'].nunique()}")

print(f"\nTotal myofibroblast markers: {mdf[mdf['category'] == 'myofibroblast']['gene'].nunique()}")
print(f"Unique myofibroblast markers: {mdf[(mdf['category'] == 'myofibroblast') & (mdf['other_categories?'] == 'unique')]['gene'].nunique()}")

Total muscle markers: 270
Unique muscle markers: 207

Total fibroblast markers: 254
Unique fibroblast markers: 166

Total myofibroblast markers: 111
Unique myofibroblast markers: 19

In [45]:
total_myo = mdf[mdf['category'] == 'muscle']['gene'].unique()
uni_myo = mdf[(mdf['category'] == 'muscle') & (mdf['other_categories?'] == 'unique')]['gene'].unique()

shared = list(set(total_myo) - set(uni_myo))

print(", ".join(shared))

HTRA1, PARVA, FBXL7, C1QTNF1, IGFBP5, CCL2, COL6A1, LAMB2, NID2, MEDAG, LAMB1, TNS2, BGN, TPM1, FLNC, PHLDB1, COL12A1, HSPB6, HSPB2, LMOD1, SULF1, MMP2, DES, ISLR, COL5A1, TIMP3, CRYAB, CALD1, COL4A1, C1QTNF5, TMEM47, PRKG1, FN1, SRPX2, COL1A1, RASL12, NNMT, COL4A2, POSTN, COX7A1, TPM2, MXRA5, ANGPTL2, PPP1R3C, SYNPO2, COL16A1, SGCD, PALLD, FSTL1, LAMA2, LUM, COL1A2, FBN1, PRRX1, NGF, MRGPRF, FKBP10, COL5A2, COL3A1, MEOX1, OLFML3, EDNRA, ENO3

In [48]:
display(mdf[mdf['gene'] == 'COL1A1'])

,gene,cell_type,source,category,other_categories?
9,COL1A1,Fibroblast Skin Human,CellMarker,fibroblast,"muscle, myofibroblast"
77,COL1A1,Fibroblasts,Panglao,fibroblast,"muscle, myofibroblast"
325,COL1A1,Myoblasts,Panglao,muscle,"fibroblast, myofibroblast"
617,COL1A1,Myofibroblasts,Panglao,myofibroblast,"fibroblast, muscle"